### PR TITLE
Bump lerna to 6.x and typescript to 4.x

### PR DESCRIPTION
**Pull request by sammys**
This is task 1 from [#356](https://github.com/stampit-org/stampit/issues/356)

### CODE REVIEW

**Comment by sammys** [comment]
> Thanks! Awesomesause :)
> 
> I trust your judgements, so I skipped reviewing all the 37 files and 40,000 lines. :)

In this case I'd say that was a wise choice hehe. It was predominantly TS compiling differently and maybe even eslint reformatting everything.
 
> Would it help if I give you more privileged access to this project?

Might save you from dealing with boilerplate changes like this one. Even if you do give me that level of access I reckon your review might be necessary for the upcoming type changes since there's a chance I won't cover edge cases you know about.

**Comment by koresar** [comment]
Makes sense. Then I'll just wait for the next PRs.

I'm super pumped about this whole TS thing. Would be very useful!

**Comment by koresar** [comment]
@sammys not sure, but looks like I've given you Admin access to this repo. Enjoy.

**Comment by sammys** [comment]
Moved the issue post from stampit to #84

**Pull request merged**
