### PR TITLE
Initialization

### PR DESCRIPTION
**Pull request by koresar**
* Kill Babel, write in ES5 instead
* Use jshint instead of eslint
* Implement `compose` and `core` with perf optimizations
* Implement `check-compose` and use it in `compose`
* Drop node <=0.12 support

### CODE REVIEW

**Comment by FredyC** [comment]
Huh, jshint ? Well I see we are moving backwards, good luck then :)

**Comment by koresar** [comment]
Unfortunately, recently I don't have enough free time to fight babel, transpilation, browser features support, performance and the dozens of other bugs we had in the past.

We'll move to >=ES6 and eslint same day all browsers support ES6. :) Currently, none of them does http://caniuse.com/#search=ES6

**Comment by koresar** [comment]
Less is more.
KISS
etc

**Comment by FredyC** [comment]
Well do you realize that this is never ending battle? Once all browsers implement ES6, there will be ES7 & ES8 which will feel same way cool.

As I said, good luck, I wont be helping with prehistoric stuff, that's not interesting enough for me.

**Comment by koresar** [comment]
Hi.

Sorry coming back that late. Life is busy recently.
Thanks for the feedback.

There is a reason lodash v4 is written in ES5, and lodash v3 is in ES3. It's ease of development, deployment, bundle size, and performance. What I want to achieve - is less time waste on new cool stuff. 

Do you have any concrete proposals?

Btw, do you find the `jest` good choice?

**Comment by FredyC** [comment]
I personally don't use Lodash anymore. Usually there isn't many functions that I would really need. I think that stampit can get rid of that dependency too. And btw there is also [lodash for ES6](https://www.npmjs.com/package/lodash-es) in case you missed it so I missing point with that.

You can just use the Bublé and get transpilation without hassle really. It's a matter of 5 minutes, especially since it has been already done on stampit repo. I don't understand why would throw that experience away and went on figuring out some prehistoric path from scratch.

Not even talking about getting rid of you ESLint which means throwing away a lot of helpful rules.

I haven't used Jest yet, so I don't have an opinion there except that I don't like much `describe / it` pattern that much anymore.

**Pull request merged**
