### PR TITLE
[WIP] Typescript port

### PR DESCRIPTION
**Pull request by PopGoesTheWza**

### CODE REVIEW

**Comment by koresar** [comment]
Wow! this is AWESOME!

**Comment by PopGoesTheWza** [comment]
TODO:
[ ] complete `@stamp/arg-over-prop` first pass of TS transform
[ ] add npm `build`script (and the relevant per package `tsconfig.json` (which should make Travis happy)
[ ] make `.js` files to be produced in the (new) `dist` folder
[ ] make `.d.ts` files to be produced in the (new) `types` folder
[ ] consolidate and enhance common type signature, either in `@stamp/is` (which is the package every other one depends on) or a new and dedicated `@stamp/typescript-typings` 
[ ] adapt npm scripts `lint` & `lint-fix` if necessary
[ ] add npm script `dryrun` [(see npm doc)](https://docs.npmjs.com/cli/publish) if necessary and adapt `npmignore` if necessary

Note: I am **not** touching `check-compose`, and that's on purpose! ;)

**Comment by PopGoesTheWza** [comment]
@koresar This is likely something silly I did wrong... I broke the default exports upon which all tests rely on.

**Comment by koresar** [comment]
Sorry, my expertise is low in this area.

**Comment by PopGoesTheWza** [comment]
Hum... [export = and import = require()](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require)

## The problem

So current `@stamp` packages use the classic *default export* CommonJS syntax:

```javascript
const anyName = require("thisModuleOnlyExportASingleDefault");

module.exports = somethingAsDefaultExport
```

This syntax is not compatible with what Typescript typical/recommended syntax produces:

### `export`

```typescript
export const SomeNamedExport
export default SomeNamedExport // effectively exported with the name 'default'
```

Which is roughly compiled into the following javascript:

```javascript
Object.defineProperty(exports, "__esModule", { value: true });
exports.SomeNamedExport;
exports.default = exports.SomeNamedExport;
```

### `import`

```typescript
import { compose } from '@stamp/compose'; // import named export
import nameForMyDefaultImport from '@stamp/compose'; // import default
```

Which is roughly compiled into the following javascript:

```javascript
const compose_1 = require("@stamp/compose");
```
Where `compose_1` is generated at compilation and each reference to `compose` becomes `compose_1.compose`. Default imports are resolved in a similar fashion but uses the value of `compose_1.default`

## Options

Thus there is a dilemma (with possibly more than two alternatives):

1. break things and have `@stamp` packages import/export compatible with what Typescript produces (and marginally have a syntax compatible with esmodules)
2. write typescript code so that the compiled js remains compatible with current interface
3. limit typescript support to manually crafted/edited/maintained `.d.ts` files

### Break import convention

The **first option** impacts all the existing code base but is rather straightforward.

Any default import from a `@stamp` module...

```javascript
var compose = require('../packages/compose');
```

... should be edited so that it uses the `default` property from the object returned by `require()`

```javascript
var compose = require('../packages/compose').default;
```
Alternatively, since the typescript code in this PR also as named exports, one could also use this syntax:

```javascript
var { compose } = require('../packages/compose');
```

All `__test__` files have been edited in order to correctly require modules compiled from typescript.

### Twist typescript to remain compatible

The **second option** requires juggling with syntax in ugly ways and make the use of type definition clumsy. For example `isFunction` and `isStamp` from `@stamp/is`

```typescript
[...]

/**
 * @internal Checks if passed argument is considered a `function`.
 */
export type isFunction = typeof isFunction;
const isFunction = <T extends Function = SomeFunction>(value: unknown): value is T => typeof value === 'function';

module.exports = isFunction;
```

Here the `isFunction` function is set as default export (`module.exports =`) which is not understood/supported by Typescript. The `isFunction` typing needs to be defined and exported separately.

```typescript
import { isFunction } from './function';

const isfunction: isFunction = require('./function');
[...]
```

Now to use `isFunction` is `@stamp/is/stamp.ts` the function and the typing have to be imported distinctly (note that they cannot share the same name!) in a very kludgy way.

**Comment by PopGoesTheWza** [comment]
What is the difference between Push and PR Travis?

**Comment by PopGoesTheWza** [comment]
@koresar please review my comment above regarding export/import issues.

Current PR follows the first option and breaks compatibility with existing code source.

If you want, I can also push the compiled .js files if you want to inspect what the compiled code looks like.

**Comment by koresar** [comment]
Thanks for the thorough investigation.

Babel compile to the exactly same .js - `export default` becomes `module.exports.default`.
You have discovered the issue which forced me to write this project (and `stampit`) with CommonJS+ES5. Namely, the Babel.
This is why my moto is "less tooling, less configuration".
Also, this is why the famous [Sindre Sorhus](https://github.com/sindresorhus) also does not use Babel and ESLint.

But we have to have the best of both words: leave the packages compatible, and have them as TypeScript. And I believe this is a long solved problem.

This package https://github.com/sindresorhus/is is written using TS, and exports all the compatible things. See https://unpkg.com/@sindresorhus/is@1.2.0/dist/index.js

```js
"use strict";
/// <reference lib="esnext"/>
/// <reference lib="dom"/>
Object.defineProperty(exports, "__esModule", { value: true });

...

exports.default = is;
// For CommonJS default export support
module.exports = is;
module.exports.default = is;
//# sourceMappingURL=index.js.map
```

This might work. Not sure how to achieve this using the `tcs`.

**Comment by PopGoesTheWza** [comment]
@koresar Yeepee... Travis says yes now.

As per the solution from Sindre Sorhus, it seems so ovious once you've seen it.

**Comment by PopGoesTheWza** [comment]
@koresar I enhanced the proposed workaround so that `module.exports.default` is not enumerable (limiting the pollution of exported objects)

```typescript
export default compose;

// For CommonJS default export support
module.exports = compose;
Object.defineProperty(module.exports, 'default', { enumerable: false, value: compose });
```

**Comment by koresar** [comment]
Awesome work mate!

**Comment by PopGoesTheWza** [comment]
Hey! Are you sure we want it merged yet? There is still plenty of Doc related TODOs and Tipescript support is minimal at this stage.

**Comment by koresar** [comment]
Sorry for rushing! My mistake. It still says WIP. Oops

Feel free to create another PR.

**Pull request merged**
