### PR TITLE
Modernize

### PR DESCRIPTION
**Pull request by koresar**
The author of the PR is @tkvw. 

* Added rollup for exporting umd and minified builds.
* Moved sources to separate src folder.
* Changed some tests to be compatible with the /src/ folder.

### CODE REVIEW

**Comment by koresar** [comment]
@tkvw I forgot what we were talking about two days ago. Could you please remind me what problem we are solving?

**Comment by tkvw** [comment]
The need for minified/umd builds for prototyping online (for example codepen). There's need for exported browser compatible builds. 
This PR adds the possibility to express `dist:{umd:'<exportname>.js',minified:'<exportname>.min.js'}` in the package.json and it will be published as so. 

But I see failing tests in travis, will look at it later

**Comment by koresar** [comment]
Ah, yes! Thank you! I'd need to do some minor changes to the `all` package exports to follow this repo standards. Also, I'd need to add a full README to it.

Thanks! Waiting for further commits. 👍

**Comment by koresar** [comment]
Since this PR destination branch is `modernize` I'll merge it and will create a new `modernize -> master` PR.
Also, @tkvw I'll give you the write access to this repo. Please don't push to `master` :)

**Pull request merged**
